### ISSUE TITLE
chore(vscode): build/dev configs for Linux

### ISSUE THREAD

**Issue by inventor02** [sufst/vcu-gui#127]
### Description

Further to #115 

`launch.json` and `c_cpp_properties.json` need configurations added for Linux

**Comment by inventor02** [comment]
Fairly sure myself and @tgodfrey0 are the only people on this team that use Linux (😢) so mainly adding this so I don't forget but could also be useful for future years/team members

**Comment by t-bre** [comment]
I was gonna suggest this - please go ahead and make a PR!
