### ISSUE TITLE
bug(gui): 'About' window inaccessible through menu bar on Windows and Linux

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu-gui#140]
### Description
The 'About' window is currently accessed through what JUCE calls the "Apple menu," which only exists on macOS. This means that the window is inaccessible on other platforms.

### Steps To Reproduce
1. Look at menu bar.
2. No 'About' window :(

### Environment
```text
os       : Windows, Linux
compiler : msvc, gcc
```

### Expected Behaviour
'About' window is accessible in some way.

### Additional Notes
The window is accessed through the following menu on macOS:

<img width="314" alt="Screenshot 2022-11-04 at 22 36 04" src="https://user-images.githubusercontent.com/31595761/200084721-b9f1057c-dfe1-458a-978b-c3ec6d828254.png">

The window looks like this:

<img width="512" alt="Screenshot 2022-11-04 at 22 32 41" src="https://user-images.githubusercontent.com/31595761/200084394-b2ce3cf5-3317-4a07-b508-81372d9c2ae9.png">

The long hex number is the hash of the latest commit at time of building.

**Comment by t-bre** [comment]
What is the conventional way for apps to allow users to view this kind of window on Linux / Windows? It's definitely a common thing to include in apps.

**Comment by AndreasDemenagas** [comment]
> What is the conventional way for apps to allow users to view this kind of window on Linux / Windows? It's definitely a common thing to include in apps.

@t-bre What I know and I’ve heard of in other kinds of desktop apps is that this is accessible through a “Help” section in the menu bar. This can then include an “About” item. That’s usually where a Help item is also added to link to docs etc…

**Comment by t-bre** [comment]
> @t-bre What I know and I’ve heard of in other kinds of desktop apps is that this is accessible through a “Help” section in the menu bar. This can then include an “About” item. That’s usually where a Help item is also added to link to docs etc…

Now you say it, I've definitely seen this as well - this sounds like the way to go. I think we should leave it in the "Apple menu" on macOS since that is the convention there, but add it to a new "Help" menu on Windows and Linux.
