### ISSUE TITLE
bug(gui): 'About' window cannot be closed on Windows

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu-gui#143]
### Description
'About' window cannot be closed once opened on Windows.

### Steps To Reproduce
1. Open 'About' window from menu bar.

### Environment
```
os       : Windows 10
compiler : msvc
```

### Expected Behaviour
'About' window can be closed from title bar.

### Additional Notes
See discussion in #142

**Comment by GZwong** [comment]
Close button works.
