### ISSUE TITLE
bug(gui): commit hash not shown in 'About' window on Windows

### ISSUE THREAD

**Issue by t-bre** [sufst/vcu-gui#144]
### Description
'About' window does not contain commit hash on Windows. The commit hash is generated in the root CMakeLists and defined globally, so this is probably not working on Windows.

### Steps To Reproduce
1. Open 'About' window from menu bar.

### Environment
```
os       : Windows 10
compiler : msvc
```

### Expected Behaviour
Commit hash displayed in 'About' window.

### Additional Notes

Currently window looks like this:

![200356970-4ad6a44c-1160-4550-97ab-f00fbfa3102f](https://user-images.githubusercontent.com/31595761/200360043-893e981f-6919-45c2-9dba-0897814fec38.png)

It should look like this:

<img width="394" alt="Screenshot 2022-11-12 at 00 03 57" src="https://user-images.githubusercontent.com/31595761/201446107-2a0fd4ce-599f-4904-99a1-022969b8705c.png">

See discussion in #142

**Comment by t-bre** [comment]
@niketa282 at some point would you be able to run some tests on this for me:

1. What happens when you run `git rev-parse HEAD` on Windows? It should give the commit hash @ HEAD. If it does (and I'm 99% sure it should do the exact same on Windows), then...
2. The issue could be with getting the output from the command in CMake which can be checked by adding `message(${GIT_COMMIT_HASH})` after line 80 in the root CMakeLists. If that prints the hash, then...
3. The issue must be with the line `-DGIT_COMMIT_HASH=\"${GIT_COMMIT_HASH}\"`, perhaps the `-D` is a problem for MSVC and it needs to be removed?

Hopefully one of these 3 things will be the cause and that will tell us what we need to change.

**Comment by niketa282** [comment]
> @niketa282 at some point would you be able to run some tests on this for me:
> 
> 1. What happens when you run `git rev-parse HEAD` on Windows? It should give the commit hash @ HEAD. If it does (and I'm 99% sure it should do the exact same on Windows), then...
> 2. The issue could be with getting the output from the command in CMake which can be checked by adding `message(${GIT_COMMIT_HASH})` after line 80 in the root CMakeLists. If that prints the hash, then...
> 3. The issue must be with the line `-DGIT_COMMIT_HASH=\"${GIT_COMMIT_HASH}\"`, perhaps the `-D` is a problem for MSVC and it needs to be removed?
> 
> Hopefully one of these 3 things will be the cause and that will tell us what we need to change.

1. yes I see the same commit hash  `f9855b8e33340895f160b476617d392c1b0dcf7b`
2. yes this prints the same hash as well
3. Removing the `-D` I can now see the commit hash but as discussed in #142 the about window still doesn't have a title bar I assume this will be a separate issue with a separate PR?

**Comment by t-bre** [comment]
Cool thanks for checking that, I honestly have no idea why I put the -D it definitely isn't necessary! Will you make a PR to fix this?

**Comment by t-bre** [comment]
And yes, the relevant issue for the title bar is #143

**Comment by niketa282** [comment]
> And yes, the relevant issue for the title bar is #143

yup just saw that
