### ISSUE TITLE
build(windows): C4244 `int` to `float` conversion warning

### ISSUE THREAD

**Issue by niketa282** [sufst/vcu-gui#145]
### Description
 While executing msbuild ./VCU-GUI.sln on windows 27 warnings observed 

warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data

https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=msvc-170

**Comment by t-bre** [comment]
Build log:

[07-11-22 Build Log.txt](https://github.com/sufst/vcu-gui/files/9954084/07-11-22.Build.Log.txt)

**Comment by t-bre** [comment]
I think we can safely suppress most of these warnings, in whatever way we choose to. In most cases these are `int` -> `float` narrowing conversions relating to GUI code and the integer values from GUI dimensions are never going to be big enough to cause a problem.
